import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRightLeft, Clock3, Image as ImageIcon, RefreshCw, UserCheck, X } from 'lucide-react';
import MainLayout from '@/components/layouts/MainLayout';
import { useAuth } from '@/contexts/AuthContext';
import { getAllRequests, getOnlineAgentProfiles, transferRequest } from '@/lib/api';
import type { Profile, RequestDocument, VerificationRequest } from '@/types/types';
import { supabase } from '@/lib/supabase';
import { toast } from 'sonner';

type Agent = { id: string; username: string };
const teal = '#19627d';
const resolveDocument = (documents?: RequestDocument | RequestDocument[]) => Array.isArray(documents) ? documents[0] : documents;
const elapsed = (date: string | null) => { if (!date) return '—'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 1000)); const hours = Math.floor(seconds / 3600); const mins = Math.floor((seconds % 3600) / 60); return hours ? `${hours} h ${mins} min` : `${mins} min ${String(seconds % 60).padStart(2, '0')} s`; };

function RequestCard({ request, onTransfer }: { request: VerificationRequest; onTransfer: (request: VerificationRequest) => void }) {
  const document = resolveDocument(request.documents);
  const images = [document?.doc_front_url, document?.doc_back_url, document?.live_photo_url].filter(Boolean) as string[];
  const start = request.status === 'processing' ? request.processing_started_at : request.created_at;
  return <article className="neu-card p-4 space-y-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">ID de la demande</p><p className="font-mono text-xs text-foreground truncate" title={request.id}>{request.id}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[11px] font-semibold ${request.status === 'pending' ? 'bg-amber-500/15 text-amber-600' : 'bg-blue-500/15 text-blue-600'}`}>{request.status === 'pending' ? 'En attente' : 'En cours'}</span></div><div className="grid grid-cols-3 gap-2">{images.length ? images.map((src, index) => <a href={src} target="_blank" rel="noreferrer" key={src} className="group aspect-[4/3] rounded-lg overflow-hidden bg-muted border border-border"><img src={src} alt={index === 2 ? 'Photo live' : `Document ${index + 1}`} className="w-full h-full object-cover transition-transform group-hover:scale-105" /></a>) : <div className="col-span-3 rounded-lg bg-muted/50 border border-dashed border-border p-4 text-center text-xs text-muted-foreground"><ImageIcon size={18} className="mx-auto mb-1 opacity-60" />Images non disponibles</div>}</div><div className="space-y-2 text-sm"><div className="flex justify-between gap-3"><span className="text-muted-foreground">Numéro à certifier</span><strong className="text-foreground">{request.phone_to_certify}</strong></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Coach mobile</span><strong className="text-foreground text-right">{request.applicant?.username ?? request.coach_mobile ?? '—'}</strong></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Agent chargé</span><span className="inline-flex items-center gap-1.5 text-right">{request.agent ? <><UserCheck size={14} className="text-primary" />{request.agent.username}</> : <span className="text-muted-foreground">Non assigné</span>}</span></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Reçue le</span><span className="text-xs text-right">{new Date(request.created_at).toLocaleString('fr-FR')}</span></div><div className="flex justify-between gap-3"><span className="text-muted-foreground inline-flex items-center gap-1"><Clock3 size={14} />Durée</span><strong className="text-primary">{elapsed(start)}</strong></div></div><button className="neu-btn-primary w-full py-2.5 text-sm inline-flex items-center justify-center gap-2" onClick={() => onTransfer(request)}><ArrowRightLeft size={16} />Transférer</button></article>;
}

export default function SupervisorQueuePage() {
  const { profile } = useAuth();
  const [requests, setRequests] = useState<VerificationRequest[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [selected, setSelected] = useState<VerificationRequest | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [transferring, setTransferring] = useState(false); const [, tick] = useState(0);
  const load = useCallback(async () => { try { const [all, available] = await Promise.all([getAllRequests(200), getOnlineAgentProfiles()]); setRequests(all.filter(r => r.status === 'pending' || r.status === 'processing')); setAgents(available); } catch { toast.error('Impossible de charger le fil d’attente'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); const timer = window.setInterval(() => tick(v => v + 1), 1000); const channel = supabase.channel(`supervisor-queue-live-${profile?.id ?? 'public'}`).on('postgres_changes', { event: '*', schema: 'public', table: 'verification_requests' }, load).on('postgres_changes', { event: '*', schema: 'public', table: 'profiles', filter: 'role=eq.agent' }, load).subscribe(); return () => { window.clearInterval(timer); supabase.removeChannel(channel); }; }, [load, profile?.id]);
  const processing = useMemo(() => requests.filter(r => r.status === 'processing'), [requests]); const pending = useMemo(() => requests.filter(r => r.status === 'pending'), [requests]);
  const doTransfer = async (agentId: string) => { if (!selected) return; setTransferring(true); const ok = await transferRequest(selected.id, agentId); if (ok) { toast.success('Demande transférée avec succès'); setSelected(null); await load(); } else toast.error('Le transfert a échoué'); setTransferring(false); };
  if (loading) return <MainLayout><div className="min-h-[60vh] flex items-center justify-center text-muted-foreground">Chargement du fil d’attente…</div></MainLayout>;
  const column = (title: string, subtitle: string, list: VerificationRequest[], tone: string) => <section className="min-w-0"><div className="flex items-center justify-between mb-4"><div><h2 className="text-lg font-bold text-foreground">{title}</h2><p className="text-xs text-muted-foreground mt-0.5">{subtitle}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone}`}>{list.length}</span></div>{list.length ? <div className="space-y-4">{list.map(request => <RequestCard key={request.id} request={request} onTransfer={setSelected} />)}</div> : <div className="neu-card py-16 text-center text-sm text-muted-foreground">Aucune demande dans cette colonne.</div>}</section>;
  return <MainLayout><div className="max-w-7xl mx-auto space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-foreground">Fil d’attente</h1><p className="text-sm text-muted-foreground mt-1">Suivi en temps réel des demandes actives et des transferts.</p></div><button className="neu-btn px-3 py-2 text-sm flex items-center gap-2" onClick={() => { setRefreshing(true); load(); }}><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} />Actualiser</button></div><div className="grid grid-cols-2 gap-4 max-w-xl"><div className="neu-card py-3 px-4"><p className="text-2xl font-bold text-primary">{processing.length}</p><p className="text-xs text-muted-foreground">En cours de traitement</p></div><div className="neu-card py-3 px-4"><p className="text-2xl font-bold text-amber-600">{pending.length}</p><p className="text-xs text-muted-foreground">En attente</p></div></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{column('En cours de traitement','Demandes actuellement prises en charge par un agent',processing,'bg-blue-500/15 text-blue-600')}{column('En attente','Demandes reçues sans agent assigné',pending,'bg-amber-500/15 text-amber-600')}</div><div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" hidden={!selected}><div className="neu-card w-full max-w-md bg-background"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold text-foreground">Transférer la demande</h2><p className="text-sm text-muted-foreground mt-1">{selected?.id}</p></div><button className="neu-btn p-2" onClick={() => setSelected(null)}><X size={18} /></button></div><p className="text-sm text-muted-foreground mt-4">Choisissez un agent libre actuellement disponible.</p><div className="mt-4 space-y-2">{agents.filter(a => a.id !== selected?.agent_id).map(agent => <button key={agent.id} disabled={transferring} onClick={() => doTransfer(agent.id)} className="w-full neu-btn px-4 py-3 flex items-center justify-between text-left"><span className="flex items-center gap-3"><span className="w-9 h-9 rounded-full bg-primary/15 flex items-center justify-center text-primary font-bold">{agent.username[0]?.toUpperCase()}</span><span><span className="block font-semibold text-foreground">{agent.username}</span><span className="block text-xs text-green-600">Disponible · En ligne</span></span></span><ArrowRightLeft size={17} className="text-primary" /></button>)}{agents.length === 0 && <p className="py-6 text-center text-sm text-muted-foreground">Aucun agent disponible.</p>}</div></div></div></div></MainLayout>;
}
